apiVersion: v1
kind: Secret
metadata:
  name: dbpass
type: Opaque
data:
  password: YWJjZGVmZzEyMw==
---
apiVersion: v1
kind: Secret
metadata:
  name: apikey
type: Opaque
data:
  key: MnI0LTBKSklmMzQwLTNrdixLMTIyMzQgLW4K