apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-flask-app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-flask-app1
  template:
    metadata:
      labels:
        app: kube-flask-app1
    spec:
      containers:
      - name: kube-flask-app1
        image: nserd/flask-app1:v1
        ports:
        - containerPort: 5000
          protocol: TCP

