apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-flask-app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-flask-app1
  template:
    metadata:
      labels:
        app: kube-flask-app1
    spec:
      volumes:
      - name: logs-storage
        persistentVolumeClaim:
          claimName: flask-app1-pvc
      containers:
      - name: kube-flask-app1
        image: nserd/flask-app1:v3
        volumeMounts:
          - mountPath: "/flask-app/logs"
            name: logs-storage
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
          - name: "POD_IP"
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: "LOG_LEVEL"
            value: "DEBUG"
          - name: "DB_HOST"
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: DB_HOST
          - name: "DB_USER"
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: DB_USER
          - name: "DB_PASS"
            valueFrom:
              secretKeyRef:
                name: dbpass
                key: password
          - name: "API_KEY"
            valueFrom:
              secretKeyRef:
                name: apikey
                key: key
        

